dfinity/quill

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, tests/run.sh
Build windows binary in both CI and release.
=> Support windows build

Cargo.toml, src/commands/mod.rs, src/commands/public.rs, tests/commands/public-ids.sh, tests/outputs/public-ids.txt
This can be used to verify the account_id of a principal.
=> Add an option to public-ids to pass the principal.

README.md
It is past midnight, so I might have gotten the "reasonable" wrong.
=> Readme: typo, grammar and semantic fixes

src/commands/request_status.rs, src/commands/send.rs, src/lib/mod.rs
=> Allow the IC_URL to be specified using an environment variable

src/commands/neuron_manage.rs
=> Allow some symbolic constants in place of dissolve delay seconds

src/commands/mod.rs, src/commands/public.rs, src/commands/transfer.rs, src/lib/mod.rs
And provide a hint to use --pem-file <pem-file>
=> Add an error message when attempting to transfer from the anonymous principal.

Cargo.lock, Cargo.toml, src/commands/generate.rs, src/commands/mod.rs, src/commands/public.rs, src/commands/send.rs, src/lib/mod.rs
This is bip39 and keysmith compatible.
=> Add a generate command to create and recovery keys.

Cargo.lock, Cargo.toml, src/commands/generate.rs, src/commands/mod.rs, src/lib/mod.rs, src/main.rs
Provides an option to use the seed file directly instead of the PEM file.
=> Provide seed file option

Cargo.lock, Cargo.toml, candid/governance.did, default.nix, src/commands/neuron_manage.rs, src/commands/send.rs, tests/commands/neuron-manage-merge.sh, tests/outputs/neuron-manage-merge.txt
This functionality has not been released yet for governance, but once it arrives then this PR will add the functionality needed to test it more fully on the testnet, and then later for users to use on mainnet until the NNS Dapp and then the Ledger Nano App are updated.
=> [IC-842] Add support for the merge_neurons management command

Cargo.lock, Cargo.toml, src/commands/mod.rs, src/commands/qrcode.rs, src/lib/mod.rs, src/lib/qr.rs, src/main.rs
This removes the dependency on quill-qr.
=> Add support for generating QR codes directly.

candid/governance.did, src/commands/update_node_provider.rs, tests/outputs/update-node-provider.txt
The `update_node_provider` function was marked as a `query` function by mistake.
=> Change update_node_provider to be an update function

src/commands/neuron_manage.rs, src/lib/mod.rs, src/lib/qr.rs
=> Add EC PARAMTERS to PEM file to be compatible with dfx.

Cargo.lock, Cargo.toml, src/commands/neuron_manage.rs, tests/commands/neuron-manage-follow.sh, tests/outputs/neuron-manage-follow.txt
This PR adds support for the neuron management FOLLOW operation.
=> Neuron follow

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib/mod.rs
Credit to @lau-bin. See discussions in #123.
This PR also includes:
- A new patch version will be released.
- CHANGELOG file is added.
=> fix: EC PARAMETERS

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/cli-reference/index.md, docs/cli-reference/quill-account-balance.md, docs/cli-reference/quill-claim-neurons.md, docs/cli-reference/quill-generate.md, docs/cli-reference/quill-get-neuron-info.md, docs/cli-reference/quill-get-proposal-info.md, docs/cli-reference/quill-list-neurons.md, docs/cli-reference/quill-list-proposals.md, docs/cli-reference/quill-neuron-manage.md, docs/cli-reference/quill-neuron-stake.md, docs/cli-reference/quill-parent.md, docs/cli-reference/quill-public-ids.md, docs/cli-reference/quill-qr-code.md, docs/cli-reference/quill-replace-node-provider-id.md, docs/cli-reference/quill-scanner-qr-code.md, docs/cli-reference/quill-send.md, docs/cli-reference/quill-transfer.md, docs/cli-reference/quill-update-node-provider.md
This PR creates CLI references that we can pull into dfinity/portal
=> chore: add CLI reference docs to pull into portal

docs/cli-reference/quill-neuron-manage.md, src/commands/neuron_manage.rs, tests/commands/neuron-manage-vote.sh, tests/outputs/neuron-manage-vote.txt
Add the ability to vote.
Hand tested and automated test.
- [x ] I have made corresponding changes to the documentation in src/docs.
=> Add the ability to vote.

candid/governance.did, candid/gtc.did, candid/ledger.did, candid/registry.did
Update the candid files.  Some commands e.g. RegisterVote were returning a type warning because the candid was stale.
Hand testing. cargo test. make test.
- [X ] I have made corresponding changes to the documentation in src/docs.
=> Update candid files.

CHANGELOG.md, Cargo.lock, Cargo.toml, src/commands/neuron_manage.rs, src/commands/neuron_stake.rs, src/commands/public.rs, src/commands/request_status.rs, src/commands/send.rs, src/lib/mod.rs, src/lib/signing.rs
Cut a major release.
Update ic dependencies (candid, agent-rs, crates from mono-repo).
CI
~- [ ] I have made corresponding changes to the documentation in src/docs.~
=> chore: update deps and release v0.3.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Bumps the version number and updates the CHANGELOG
=> chore: release 0.3.1

CHANGELOG.md, docs/cli-reference/sns/quill-sns-pay.md, src/commands/sns/pay.rs, tests/commands/sns-pay.sh, tests/outputs/sns-pay.txt
=> fix: require --ticket-creation-time in sns pay

Cargo.lock
=> chore: Update `tempfile` and `cpufeatures`

docs/cli-reference/quill-parent.md, src/main.rs
=> docs: Add HSM docs

LICENSE
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Copyright owner missing in license file. 
N/A
=> Adding license owner to license file

.github/workflows/e2e.yml, e2e/utils/_.bash, scripts/workflows/provision-darwin-e2e.sh, scripts/workflows/provision-linux-e2e.sh
Also configures dfxvm in the isolated home directory in the standard test setup.
=> fix: install dfx using setup-dfx action

src/commands/generate.rs, src/commands/mod.rs, src/commands/neuron_manage.rs, src/commands/neuron_stake.rs, src/commands/public.rs, src/commands/qrcode.rs, src/commands/request_status.rs, src/commands/send.rs, src/commands/sns.rs, src/commands/sns/configure_dissolve_delay.rs, src/commands/sns/follow_neuron.rs, src/commands/sns/neuron_id.rs, src/commands/sns/pay.rs, src/commands/transfer.rs, src/lib/ledger.rs, src/lib/mod.rs, src/main.rs
This PR removes all the places that Quill panics in cases other than programmer error. It also cleans up some of the clippy::pedantic lints.
=> fix: Remove panics

src/lib/ledger.rs
Consistency with other Identity impls
=> fix: Export key in expanded form

CHANGELOG.md, Cargo.lock, src/lib/format/mod.rs, src/lib/format/sns_governance.rs, src/lib/format/sns_root.rs, src/lib/format/sns_swap.rs, src/lib/format/sns_wasm.rs, src/lib/mod.rs
Finishes the feature started in #220.
=> feat: Implement rich output for `quill sns`

src/lib/format/ckbtc.rs, src/lib/format/nns_governance.rs, src/lib/mod.rs
This adds a display format for a few fields that got missed, and cleans up some externally contributed formatting code.
=> feat: Update display output

Cargo.lock, Cargo.toml, candid/ckbtc_minter.did, candid/governance.did, candid/icrc1.did, candid/ledger.did, candid/registry.did, candid/sns-governance.did, candid/sns-root.did, candid/sns-swap.did, candid/snsw.did, src/commands/sns/make_upgrade_canister_proposal.rs, src/lib/format/nns_governance.rs, src/lib/format/sns_governance.rs, tests/output/default/list_neurons/many.txt, tests/output/default/list_neurons/simple.txt, tests/output/default/sns/make_proposal/upgrade.txt, tests/output/default/sns/make_proposal/upgrade_arg.txt, tests/output/default/sns/make_proposal/upgrade_summary_path.txt, tests/output/ledger/list_neurons/many.txt, tests/output/ledger/list_neurons/simple.txt
This importantly adds the new topic fields in SNS proposals.
=> chore: Update to 5ebf5a3922383cbb937d0fbc0509aec445341036
