.github/workflows/release.yml
Makefile

This will build release binaries whenever a new tag is pushed.
It also builds a static binary for Linux, which can be used on Windows under WSL too.

Build release binary

---

src/commands/neuron_stake.rs
tests/commands/15.sh
tests/outputs/15.txt

Some people prefer to use a raw numeric `nonce` while staking / topping up the neurons. This PR adds this option.

adds a nonce parameter to neuron staking

---

src/commands/neuron_stake.rs

At the moment seed holders must claim their neurons using `dfx` and `dcid`. However, `quill` is inches away from being able to be used for just claiming a neuron. I've enabled support for this somewhat special case by interpret a staking amount of "0 to mean that there is no initial transfer involved, only a claiming operation.

Allow neuron-stake to be using for claiming seed neurons

---

src/commands/neuron_manage.rs
tests/commands/neuron-manage-spawn.sh

Currently, if you stake, split or spawn a neuron, you get the neuron id in candid notation, where the underscore is used as a thousand separator. This PR makes quill accept this notation.

Accept underscores in neuron id

---

Cargo.lock
Cargo.toml

Random feature is not needed for quill. This removes a lot of unnecessary dependencies.

remove random feature from candid

---

.github/workflows/release.yml

Remove `v7` in ARM release, which causes seg fault when running in Raspberry Pi.
I cannot test this directly. But I am able to test the `didc` binary with the same change. `armv7` seg faults in Pi, and `arm` works fine.

Fix ARM release

---

tests/commands/account-balance.sh
tests/commands/fixed-pipe.sh
tests/commands/list-neurons-many.sh
tests/commands/list-neurons.sh
tests/commands/neuron-manage-a.sh
tests/commands/neuron-manage-add-hot-key.sh
tests/commands/neuron-manage-disburse-stop-dissolving.sh
tests/commands/neuron-manage-merge-maturity.sh
tests/commands/neuron-manage-spawn.sh
tests/commands/neuron-manage-split.sh
tests/commands/neuron-manage.sh
tests/commands/neuron-stake-with-name.sh
tests/commands/public-ids.sh
tests/commands/transfer-e8s.sh
tests/commands/transfer-icp-and-e8s.sh
tests/commands/transfer-with-fees-and-memo.sh
tests/commands/transfer-with-fees.sh
tests/commands/transfer.sh

Namely, rather than assumes that binaries are in `../target`, use `CARGO_TARGET_DIR` if it has been defined.

Generalize tests to work in more environments

---

default.nix

The current `cargoSha256` seems to be wrong:
```
hash mismatch in fixed-output derivation '/nix/store/xvx24m6387266pixnvcxabxpxad70w5d-quill-0.2.9-vendor.tar.gz':
wanted: sha256:13x8pbvv45a7b7s87x266bppax3awanpbz94h1hf2qwwj4xaarxl
got:    sha256:1x0gsg62nmf5l9avfd18qzdc9i9lm2y62qgkj9iwshgdfjqzavvy
```

Fix cargoSha256 mismatch in default.nix

---

candid/governance.did
src/commands/mod.rs
src/commands/update_node_provider.rs
tests/commands/update-node-provider.sh
tests/outputs/update-node-provider.txt

@chmllr @Dfinity-Bjoern This implements the following command:
```
quill update-node-provider --reward-account <account id>
```
However, when you pipe this through `send --dry-run`, the `reward_account` is always `null`. I'm not familiar enough with the Rust candid library to know why it's failing to encode the account identifier.

[RES-40] Implement update-node-provider command

---

Cargo.lock
Cargo.toml
default.nix
src/commands/generate.rs
src/commands/mod.rs
src/commands/neuron_manage.rs
src/commands/public.rs
src/commands/request_status.rs
src/commands/send.rs
src/commands/transfer.rs
src/lib/mod.rs
src/lib/signing.rs
src/main.rs

I removed the (panic|unwrap|expect)s from the project on bad user inputs and similar errors that are expected to happen and should be reported with a human friendly message. Some of my changes are redundant, e.g. the unwrap on opts that get also validated by validators,  but the new code is not much more than unwrapping.
I also added some tests in main.rs that helped me validating my changes to that file.

TOB-DQK-007 remove panics

---

src/commands/neuron_manage.rs
tests/commands/neuron-manage-clear.sh
tests/outputs/neuron-manage-clear.txt

This is needed to clear ManageNeuron followees, since this cannot be done using the NNS Dapp.

Add neuron-manage $NEURON --clear-manage-neuron-followees

---

src/commands/send.rs
src/lib/signing.rs
tests/outputs/account-balance.txt
tests/outputs/get-neuron-info.txt
tests/outputs/get-proposal-info.txt
tests/outputs/list-neurons-many.txt
tests/outputs/list-neurons.txt
tests/outputs/list-proposals.txt

Resolves SDK-491. All queries are performed as update equivalents, in order to certify their responses.

feat: Convert all query calls to update calls

---

candid/registry.did
src/commands/mod.rs
src/commands/replace_node_provide_id.rs
src/lib/mod.rs
tests/commands/replace-node-provider-id.sh
tests/outputs/replace-node-provider-id.txt

Node provider can replace its ID in the targeted Node Operator Record.
The message should be signed with the credential (likely to be a HSM key) of current node provider id.
This is the first command making call to the registry canister. The candid file is added.

feat: support replace node provider id

---

Cargo.lock
Cargo.toml
src/commands/neuron_manage.rs
src/commands/send.rs
src/commands/transfer.rs

Several rustsec advisories are triggered by the current dependency tree. This PR upgrades the agent and IC, and updates several dependencies including Candid. The final (avoidable) advisory, against libsecp256k1, is handled by #128.

chore: Upgrade dependencies

---

Cargo.lock
Cargo.toml
src/lib/mod.rs

We currently use the crate `tiny_hderive` for our bip32 key derivations. Unfortunately this crate is GPL-3, rendering it unusable in this Apache-2.0 repo. This PR replaces it with the equivalent `bip32` crate. For convenience it also replaces `libsecp256k1` with `k256`, and as that is what agent-rs uses, there is one fewer dependency.

chore: Replace tiny_hderive with bip32

---

src/commands/mod.rs

A bug was introduced with `quill generate` in #126 around the repetition of a `clap` argument. Because the `pem_file` and `seed_file` parameters were repeated twice in the same command, running the command would crash. This fixes it by removing the common flags from the command, as they are not used at all.

Fix `quill generate` arg

---

candid/governance.did
e2e/tests-quill/create_neuron.bash
e2e/utils/setup_nns.bash
src/commands/neuron_manage.rs
tests/commands/neuron-manage-leave-community-fund.sh
tests/outputs/neuron-manage-leave-community-fund.txt
tests/outputs/neuron-manage-spawn.txt

feat: Add ability to leave community fund

---

docs/cli-reference/index.md
docs/cli-reference/sns/quill-sns-get-sale-participation.md
src/commands/sns.rs
src/commands/sns/get_sale_participation.rs
tests/commands/sns-get-sale-participation.sh
tests/outputs/sns-get-sale-participation.txt

Adds the `quill sns get-sale-participation` command as a frontend for `swap.get_buyer_state`.

feat: `quill sns get-sale-participation`

---

Cargo.lock
Cargo.toml
docs/cli-reference/ckbtc/quill-ckbtc-balance.md
docs/cli-reference/quill-account-balance.md
docs/cli-reference/quill-get-neuron-info.md
docs/cli-reference/quill-get-proposal-info.md
docs/cli-reference/quill-list-proposals.md
docs/cli-reference/quill-send.md
docs/cli-reference/sns/quill-sns-balance.md
docs/cli-reference/sns/quill-sns-list-deployed-snses.md
docs/cli-reference/sns/quill-sns-status.md
src/commands/account_balance.rs
src/commands/get_neuron_info.rs
src/commands/get_proposal_info.rs
src/commands/list_proposals.rs
src/commands/send.rs

Currently, if you run `quill list-neurons | quill send -`, Quill will print the call information, ask y/n, and then exit without letting you answer. This is how pipes work, but it is confusing for users who don't know that. This PR makes it so that if quill is being piped to, it will instead exit tellling users to use the `--yes` flag. To improve the ergonomics of the `quill | quill send -` use-case, all `--yes` flags have also been shortened to `-y`.

feat: Shorten -y flag and check for tty

---

docs/cli-reference/quill-neuron-stake.md
docs/cli-reference/quill-transfer.md
src/commands/neuron_stake.rs
src/commands/transfer.rs
tests/commands/neuron-stake-nonce.sh
tests/commands/transfer-e8s-2.sh
tests/outputs/neuron-stake-nonce.txt
tests/outputs/transfer-e8s-2.txt

This was present for ckBTC and SNS, but not for base NNS commands.

feat: Add `--from-subaccount` to transfer/stake

---

CHANGELOG.md
docs/cli-reference/ckbtc/quill-ckbtc-balance.md
docs/cli-reference/ckbtc/quill-ckbtc-withdrawal-address.md
docs/cli-reference/quill-account-balance.md
docs/cli-reference/sns/quill-sns-balance.md
src/commands/account_balance.rs
src/commands/ckbtc/balance.rs
src/commands/ckbtc/withdrawal_address.rs
src/commands/mod.rs
src/commands/sns/balance.rs
tests/commands/account-balance-2.sh
tests/outputs/account-balance-2.txt

If `quill account-balance` is used without an account ID parameter, but authenticated with `--pem-file` or similar, the account ID will be inferred.

feat: Detect the key in `quill account-balance`

---

CHANGELOG.md
src/commands/account_balance.rs
src/commands/neuron_stake.rs
src/commands/transfer.rs
src/lib/mod.rs
tests/commands/account-balance-icrc1.sh
tests/commands/transfer-icrc1.sh
tests/outputs/account-balance-icrc1.txt
tests/outputs/transfer-icrc1.txt

This extends the ICRC-1 account ID support found in `quill sns` and `quill ckbtc` to `quill transfer` and `quill account-balance`. This incidentally enables bare principals to be used there too.

feat: Accept ICRC-1 account IDs

---

docs/cli-reference/quill-send.md
src/commands/send.rs
tests/commands/ckbtc-retrieve-btc-already-transferred.sh
tests/commands/sns-make-proposal.sh
tests/commands/transfer.sh

If `quill send` is run without a filename, it checks whether stdin is a tty, and if it isn't, assumes that `-` was intended.
Fixes #74.

feat: infer `-` on quill send if being piped

---

CHANGELOG.md
docs/cli-reference/quill-neuron-manage.md
src/commands/neuron_manage.rs
src/lib/mod.rs
tests/commands/neuron-manage-disburse-somewhat-to-someone.sh
tests/outputs/neuron-manage-disburse-somewhat-to-someone.txt

Adds the `--disburse-amount` and `--disburse-to` flags to `quill neuron-manage`, for scenarios other than disbursing the full amount to the controller. 
Fixes #43, fixes #44.

feat: More disbursal flags

---

README.md

Updates the examples in README.md to no longer have named arguments in the middle of the command.
Fixes #148.

chore: Update examples in readme

---

CHANGELOG.md
docs/cli-reference/quill-neuron-stake.md
src/commands/neuron_stake.rs
tests/commands/neuron-stake-only.sh
tests/outputs/neuron-stake-only.txt

Currently, `quill neuron-stake` produces two messages if passed `--amount`, but skips the transfer message if `--amount` is omitted. This is unintuitive behavior as the two-message form is the default but the command syntax is opt-in, and any errors are likely to be very confusing. This PR (breakingly) requires a new explicit `--already-transferred` flag to use `quill neuron-stake` in one-message form.

feat!: Add explicit no-transfer parameter to neuron-stake

---

docs/cli-reference/quill-parent.md
src/lib/mod.rs
src/main.rs

Currently Quill references Nitrokey in several places, including environment variable names. This is misleading to users because Quill doesn't require OpenSC's PKCS#11 implementation, let alone any particular OpenSC-compatible key, so it could just as easily be used with e.g. Yubikey. This PR replaces the `NITROHSM_*` variables with `QUILL_HSM_*` variables (while still accepting the old ones for compatibility), and removes mention of Nitrokey from the PIN input prompt. 
Additionally, `--hsm-*` flags now imply `--hsm`, with `--hsm` only being needed to accept the default values for the other flags.

feat: Remove explicit mentions of NitroHSM

---

docs/cli-reference/index.md

This PR fixes a broken link at [docs/cli-reference/index.md](https://github.com/dfinity/quill/blob/master/docs/cli-reference/index.md?plain=1#L20
)
Build passes on dfinity/portal after applying the change.

Fix broken link

---

.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/release.yml

This adds caching to the CI and release workflows, updates task outputs to use `$GITHUB_ENV` instead of `::set-env` et al, and makes a couple things more consistent.

chore: Update CI

---

.github/workflows/release.yml

We release for more targets than we test for, and so occasionally don't catch things like the arm32 segfault until release day. This PR runs the release action on every commit like [dfinity/sdk](https://github.com/dfinity/sdk) does.

chore: Always run release action

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib/mod.rs
tests/commands/account-balance-icrc1.sh
tests/commands/transfer-icrc1.sh
tests/outputs/ckbtc-withdrawal-address.txt

Previously, non-default account IDs were an oversized principal that included the subaccount; now the WG has standardized on an alternative format that visually separates the subaccount from the principal. This is technically a breaking change but it is unlikely anyone had a chance to use the old format before it got replaced. 
Do not merge before dfinity/ICRC-1#98.

feat: Update to new ICRC-1 account format

---

docs/cli-reference/ckbtc/quill-ckbtc-balance.md
docs/cli-reference/ckbtc/quill-ckbtc-retrieve-btc-status.md
docs/cli-reference/ckbtc/quill-ckbtc-retrieve-btc.md
docs/cli-reference/ckbtc/quill-ckbtc-transfer.md
docs/cli-reference/ckbtc/quill-ckbtc-update-balance.md
docs/cli-reference/ckbtc/quill-ckbtc-withdrawal-address.md
src/commands/ckbtc/balance.rs
src/commands/ckbtc/retrieve_btc.rs

This extends the `quill ckbtc` command docs with examples and remarks.

docs: Extend ckBTC docs

---

Cargo.toml

This adds the necessary manifest keys for [`cargo binstall`](https://github.com/cargo-bins/cargo-binstall) to discover the quill binaries.

chore: Add support for cargo-binstall

---

CHANGELOG.md
docs/cli-reference/quill-public-ids.md
src/commands/account_balance.rs
src/commands/ckbtc/retrieve_btc.rs
src/commands/ckbtc/withdrawal_address.rs
src/commands/generate.rs
src/commands/mod.rs
src/commands/neuron_stake.rs
src/commands/public.rs
src/commands/sns/get_sale_participation.rs
src/commands/sns/get_swap_refund.rs
src/commands/sns/neuron_id.rs
src/commands/sns/pay.rs
src/commands/sns/stake_neuron.rs
src/lib/mod.rs
tests/output/default/public_ids/basic.txt
tests/output/default/public_ids/with_subaccount.txt
tests/output/ledger/public_ids/basic.txt
tests/output/ledger/public_ids/with_subaccount.txt
tests/output/main.rs
tests/output/root.rs

This adds a `--subaccount` flag to `quill public-ids`, which will display the legacy account ID and ICRC1 account ID for that subaccount.

feat: Add `--subaccount` flag to `public-ids`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands/sns/make_proposal.rs
tests/output/default/sns/make_proposal/with_blob.txt
tests/output/sns.rs

Fixes the bug described here: https://forum.dfinity.org/t/quill-transfersnstreasuryfunds-to-subaccount-always-null/28485

fix: Fix to_subaccount getting deleted and release 0.4.4

---

README.md

Update README to support v3 of the MDX parser. This is to support the migration to docusaurus v3 for the portal.

chore: update readme to support mdx v3

---

Cargo.lock
Cargo.toml
candid/governance.did
candid/sns-governance.did
candid/sns-root.did
candid/snsw.did

The candids have gotten out of date. This lead to issues with e.g. reinstalling sns-controlled canisters. This MR synchronizes them with ic master. That was an issue with SNS-Gov, but I updated a few other candids too for good measure.

Upgrade candids

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/cli-reference/index.mdx
docs/cli-reference/quill-decrypt-pem.mdx
docs/cli-reference/quill-generate.mdx
docs/cli-reference/quill-parent.mdx
src/commands/account_balance.rs
src/commands/ckbtc/balance.rs
src/commands/ckbtc/update_balance.rs
src/commands/ckbtc/withdrawal_address.rs
src/commands/claim_neurons.rs
src/commands/decrypt_pem.rs
src/commands/generate.rs
src/commands/mod.rs
src/commands/public.rs
src/commands/qrcode.rs
src/commands/sns/balance.rs
src/commands/sns/disburse.rs
src/commands/sns/disburse_maturity.rs
src/commands/sns/get_sale_participation.rs
src/commands/sns/neuron_id.rs
src/lib/ledger.rs
src/lib/mod.rs
src/main.rs
tests/output/default/base_command/need_password.txt
tests/output/default/base_command/wrong_password.txt
tests/output/default/generate/no_password.txt
tests/output/root.rs

This PR adds encrypted PEM files and generates them by default, so sensitive data is not stored in plaintext. Seed file auth is disabled; keys must be generated first. To allow using encrypted keys with other tools, the `quill decrypt-pem` command is added. 
Closes SDK-1422.

feat: Pem auth overhaul

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/cli-reference/sns/quill-sns-make-upgrade-canister-proposal.mdx
src/commands/sns/make_upgrade_canister_proposal.rs
tests/output/default/sns/make_proposal/upgrade.txt
tests/output/default/sns/make_proposal/upgrade_arg.txt
tests/output/default/sns/make_proposal/upgrade_summary_path.txt
tests/output/sns.rs

Previously there was no way to send a UpgradeSnsControlledCanister proposal that reinstalls a canister with quill. This MR adds a `--mode` flag that can be used for this purpose. The flag is required. 
Fixes [NNS1-3063](https://dfinity.atlassian.net/browse/NNS1-3063)
Automated tests have been adjusted to test all 3 cases 
[NNS1-3063]: https://dfinity.atlassian.net/browse/NNS1-3063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support reinstalling canisters (SNS)

---

docs/cli-reference/quill-generate.mdx
src/commands/generate.rs
src/lib/mod.rs

This changes the scrypt `n` parameter from the default 2^15 to 2^17, per prodsec recommendations. Changelog is unmodified as the feature hasn't been released yet, but there are no compatiblity problems either.

fix: Strengthen scrypt parameters

---

src/commands/generate.rs
tests/output/default/base_command/bad_password.txt
tests/output/root.rs

This adds a password policy to `quill generate`, per prodsec recommendation. The implemented policy is a minimum length of 8 characters.

fix: Add password policy

---

CHANGELOG.md
src/commands/claim_neurons.rs
src/lib/ledger.rs
tests/output/ledger/claim_neurons/simple.txt
tests/output/root.rs

Support was removed in the IC app in Zondax/ledger-icp#228, this removes the CLI error.

fix: Remove support for ledger neuron claiming

---

.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
.github/workflows/shellcheck.yml

Since actions-rs is archived, this removes it and unconditionally uses cross, as in dfinity/agent-rs#532

chore: update deprecated actions

---

Cargo.lock
Cargo.toml
candid/governance.did
candid/icrc1.did
candid/ledger.did
candid/registry.did
candid/sns-governance.did
candid/sns-root.did
candid/sns-swap.did
candid/snsw.did
docs/cli-reference/quill-neuron-manage.mdx
e2e/utils/setup_nns.bash
scripts/point-to-ic-repo-commit-id.sh
src/commands/neuron_manage.rs
src/lib/format/nns_governance.rs
src/lib/mod.rs
tests/output/default/list_neurons/many.txt
tests/output/default/list_neurons/simple.txt
tests/output/default/neuron_manage/set_visibility.txt
tests/output/neuron_manage.rs

Added `--set-visibility` flag to `quill neuron-manage`. Takes one of two possible values: `public` or `private`.
In a separate commit, updated this repo to point to a more recent commit in the ic repo.
Added a script to make the aforementioned chore easier.
Added set_visibility test.

feat: Set neuron visibility.

---

src/lib/format/mod.rs
src/lib/format/sns_swap.rs

This PR fixes the `display_new_sale_ticket` function by correctly treating nanosecond timestamps in `NewSaleTicketResponse.ok.creation_time` instances.
Tested manually using sns-testing.
* No, as this is a bug fix.
* No, as there are no SNS integrating tests in this repo. It does not follow from the SNS API that the `creation_time` field carries nanoseconds.

fix: Display nanosecond timestamps in `NewSaleTicketResponse` instances 
